# -*- coding: utf-8 -*-
"""Excercise1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lNzHVMtO2mbeNw6dbfWyn_kic9DSxNm
"""
📌 INTRODUCTION

This focuses on working with Python’s datetime module to handle dates and time. The goal is to take a user’s birthdate, validate the format, calculate the current age, and convert the date into European format. This exercise helps build practical understanding of date validation, error handling, string formatting, and real-world user input processing.


from datetime import datetime

def calculate_age():
    try:
        # Asking user for birth date in mm/dd/yyyy format
        birth_input = input("Enter your birth date (mm/dd/yyyy): ")

        # Validating and converting the input string to date object
        birth_date = datetime.strptime(birth_input, "%m/%d/%Y")

        # Getting today's date
        today = datetime.today()

        # Calculating age in years
        age = today.year - birth_date.year

        # Adjust age if birthday has not occurred yet this year
        if (today.month, today.day) < (birth_date.month, birth_date.day):
            age -= 1

        print(f"Your current age is: {age} years")

        # Converting to European format
        euro_format = birth_date.strftime("%d/%m/%Y")
        print(f"Your birthdate in European format: {euro_format}")

    except ValueError:
        # Handling wrong date format or invalid date
        print("Invalid date format! Please enter date as mm/dd/yyyy.")

calculate_age()

📌 CONCLUSION

I learned how to safely handle date inputs, process them using Python’s built-in functions, and manage exceptions for invalid user entries. The exercise improved my skills in working with the datetime library and formatting dates in different representations. It also strengthened my ability to implement user-friendly, error-tolerant programs.