# -*- coding: utf-8 -*-
"""Excercise2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R0Guo-1rUdOgkos4iwLmtn1KK7Gqz_Ib
"""
📌 INTRODUCTION

Exercise 2 is about identifying all prime numbers within a user-specified range. This task strengthened logical thinking, mathematical reasoning, and input validation skills. The objective is to accept two numbers, validate that they are positive integers, generate prime numbers within the range, and display them in a clean, readable format.


def is_prime(num):
    # Function checks if a number is prime
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

def prime_generator():
    try:
        # Taking range start and end from user
        start = int(input("Enter start of range: "))
        end = int(input("Enter end of range: "))

        # Validating positive integers
        if start <= 0 or end <= 0:
            print("Numbers must be positive!")
            return

        print("Prime numbers in the range:")
        count = 0

        for num in range(start, end + 1):
            if is_prime(num):
                print(num, end=" ")
                count += 1

                # Print 10 numbers per line
                if count % 10 == 0:
                    print()

        print()
    except ValueError:
        print("Invalid input! Enter positive integers only.")

prime_generator()


📌 CONCLUSION

This exercise helped reinforce the concept of loops, condition checks, and prime number logic. I learned how to validate numeric input, efficiently detect prime numbers, and present output neatly. It also improved my understanding of algorithm design and building functions that handle edge cases gracefully.