# -*- coding: utf-8 -*-
"""Excercise1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lNzHVMtO2mbeNw6dbfWyn_kic9DSxNm
"""

from datetime import datetime

def calculate_age():
    try:
        # Asking user for birth date in mm/dd/yyyy format
        birth_input = input("Enter your birth date (mm/dd/yyyy): ")

        # Validating and converting the input string to date object
        birth_date = datetime.strptime(birth_input, "%m/%d/%Y")

        # Getting today's date
        today = datetime.today()

        # Calculating age in years
        age = today.year - birth_date.year

        # Adjust age if birthday has not occurred yet this year
        if (today.month, today.day) < (birth_date.month, birth_date.day):
            age -= 1

        print(f"Your current age is: {age} years")

        # Converting to European format
        euro_format = birth_date.strftime("%d/%m/%Y")
        print(f"Your birthdate in European format: {euro_format}")

    except ValueError:
        # Handling wrong date format or invalid date
        print("Invalid date format! Please enter date as mm/dd/yyyy.")

calculate_age()