# -*- coding: utf-8 -*-
"""Excercise4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1inJ5aSbxzCM0ijDBSFcsPYVp3OFU5NBC
"""

import requests
import csv

def fetch_weather(city, api_key):
    try:
        # API endpoint
        url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric"

        # Sending GET request
        response = requests.get(url)

        # Handling invalid response
        if response.status_code != 200:
            print("Error fetching weather! Check city name or API key.")
            return None

        return response.json()

    except Exception:
        print("Network error! Unable to fetch data.")
        return None

def analyze_weather(data):
    # Extracting temperature, humidity, wind
    temp = data['main']['temp']
    humidity = data['main']['humidity']
    wind = data['wind']['speed']

    # Temperature classification
    if temp <= 10:
        summary = "Cold (≤10°C)"
    elif 11 <= temp <= 24:
        summary = "Mild (11–24°C)"
    else:
        summary = "Hot (≥25°C)"

    # Adding warnings
    if wind > 10:
        summary += " | High wind alert!"
    if humidity > 80:
        summary += " | Humid conditions!"

    return summary

def log_weather(city, filename):
    api_key = input("Enter your OpenWeatherMap API Key: ")

    data = fetch_weather(city, api_key)
    if data is None:
        return

    summary = analyze_weather(data)

    # Opening CSV file and appending new row
    with open(filename, "a", newline="") as file:
        writer = csv.writer(file)
        writer.writerow([city, data['main']['temp'], data['main']['humidity'],
                         data['wind']['speed'], summary])

    print("Weather data logged successfully!")

# Run function
city_name = input("Enter city name: ")
log_weather(city_name, "weather_log.csv")