# -*- coding: utf-8 -*-
"""Excercise3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p1C7Xk_9M9139Jx0y9bvvcam7tcQ8ZOX
"""

# Exercise 3: Student Marks Processor
# Reads marks from file, computes total, assigns grade,
# stores structured NumPy array, sorts results, writes output, and prints stats.

import numpy as np

def calculate_grade(mark):
    # Assigning grades based on rules
    if mark >= 90:
        return "A"
    elif mark >= 75:
        return "B"
    elif mark >= 60:
        return "C"
    elif mark >= 50:
        return "D"
    else:
        return "F"

def process_student_marks():
    try:
        # Reading input file
        with open("student_marks.txt.", "r") as f:
            lines = f.readlines()

        # Structured numpy array format
        dtype = [('regno', 'U20'), ('exam', 'i4'), ('coursework', 'i4'),
                 ('total', 'f4'), ('grade', 'U2')]

        data_list = []

        for line in lines:
            reg, exam, cw = line.strip().split(",")
            exam = int(exam)
            cw = int(cw)

            # Computing weighted mark (exam 70%, coursework 30%)
            total = exam * 0.7 + cw * 0.3

            grade = calculate_grade(total)

            data_list.append((reg, exam, cw, total, grade))

        # Creating numpy structured array
        students = np.array(data_list, dtype=dtype)

        # Sorting by overall mark
        students_sorted = np.sort(students, order='total')[::-1]

        # Writing results to output file
        with open("results_output.txt", "w") as out:
            for s in students_sorted:
                out.write(f"{s['regno']}, {s['total']:.2f}, {s['grade']}\n")

        # Display grade statistics
        grades = [s['grade'] for s in students]
        print("Grade Statistics:")
        for g in set(grades):
            print(f"{g}: {grades.count(g)} students")

    except Exception as e:
        print("Error occurred:", e)

process_student_marks()