# -*- coding: utf-8 -*-
"""Excercise2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R0Guo-1rUdOgkos4iwLmtn1KK7Gqz_Ib
"""

def is_prime(num):
    # Function checks if a number is prime
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

def prime_generator():
    try:
        # Taking range start and end from user
        start = int(input("Enter start of range: "))
        end = int(input("Enter end of range: "))

        # Validating positive integers
        if start <= 0 or end <= 0:
            print("Numbers must be positive!")
            return

        print("Prime numbers in the range:")
        count = 0

        for num in range(start, end + 1):
            if is_prime(num):
                print(num, end=" ")
                count += 1

                # Print 10 numbers per line
                if count % 10 == 0:
                    print()

        print()
    except ValueError:
        print("Invalid input! Enter positive integers only.")

prime_generator()